name: Deploy Portfolio to Strato

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # - name: Run Tests   #(Optional) Uncomment to run tests when testing is set up
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless

      # Linting # need to set up ESLint first an fix any issues
      # - name: Run ESLint
      #   run: npm run lint

      - name: Build for Production
        run: npm run build

      - name: Deploy to Strato SFTP
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./dist/myportfolio/browser/*"
          remote_path: ${{ secrets.SFTP_TARGET_PATH }}
